# Generated by Django 4.2.6 on 2023-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggerNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_title',
            field=models.CharField(default="Spide's Blogger", max_length=255),
        ),
    ]
